-- radar_db.sql

CREATE DATABASE RADAR;

USE RADAR;

CREAT TABLE USERS (
    USE_ID INT AUTO_INCREMENT;
    USE_NAME VARCHAR(90) NOT NULL;
    USE_ENAIL VARCHAR(90) NOT NULL;
    USE_PASSWORD VARCHAR(300) NOT NULL;
    CONSTRAINT USE_PK PRIMARY KEY(USE_ID)
);

CREATE TABLE DEVISES (
    DEV_ID INT AUTO_INCREMENT;
    DEV_USE_ID INT NOT NULL;
    DEV_NAME VARCHAR(90);
    DEV_TOKEN VARCHAR(300) NOT NULL;
    DEV_LAST_LATITUDE DECIMAL(10,8);
    DEV_LAST_LONGITUDE DECIMAL(11,8);
    DEV_LAST_SEEN_AT TIMESTAMP;
    CONSTRAINT DEV_PK PRIMARY KEY(DEV_ID);
    CONSTRAINT DEV_USE_FK FOREIGN KEY(DEV_USE_ID) REFERENCES USERS(USE_ID)
);

